[COMSUP-337] Add links to homepage sections
edgio-docs/edgio-docs pull request #1098
Opened 2024-05-10 14:46 UTC by tristanlee85

2024-05-10 14:57 UTC, tristanlee85 commented
@jsernaque You mentioned about adding a section for API references. I am happy to add them, but I think we need to review the items we currently have to slim them down before adding more.

2024-05-20 15:48 UTC, jsernaque requested changes
Broken links for: Applications sub-headings and REST API. Fix the REST API link by setting it to a full URL. 
The API sub-heading requires a path. What if we renamed it to Develop and link to the Develop page?
Suggestion: We should align the Applications landing page with the main landing page. 
Suggestion: We should increase the font on the main landing page.

2024-05-20 22:30 UTC, jsernaque commented on src/config/home/sections.ts
> +            path: '/rest_api/',
This link still returns a Page not found.

2024-05-20 23:38 UTC, tristanlee85 commented on src/config/home/sections.ts
> +            path: '/rest_api/',
Pushed a fix. I had verified this as working on my end but I think I had it cached.

2024-05-21 00:06 UTC, jsernaque approved these changes
LGTM

2024-05-21 01:41 UTC, merged