CON-2448 Asm - Amazon GuardDuty docs added, cleanup of github descrip…
edgio-docs/edgio-docs pull request #1199
Opened 2024-08-21 09:17 UTC by jakub-jarek

…tions

2024-08-21 17:10 UTC, jsernaque requested changes
Please review these suggestions.

2024-08-21 17:10 UTC, jsernaque commented on guides/applications/v7/security/asm.md
>      -   Exposed secrets.
```suggestion
```

2024-08-23 08:23 UTC, jakub-jarek commented on guides/applications/v7/security/asm.md
> +    -   {{ PRODUCT }} uses seeds to determine which network segments will be scanned. Each hostname and IP address identified through this scan is also registered as an asset.
no - seeds are above ips and hostnames in this sense...eg. you might have seed for github repo, but that github repo will have connected hostnames etc.

2024-08-23 08:24 UTC, jakub-jarek commented on guides/applications/v7/security/asm.md
>      -   Exposed secrets.
Why? Exposed secrets are targetable.

2024-08-23 08:25 UTC, jakub-jarek commented on guides/applications/v7/security/asm.md
> +    -   AWS issues.
CVEs and CWEs are already part of snyk, so this feels strange

2024-08-23 08:28 UTC, jakub-jarek commented on guides/applications/v7/security/asm.md
> +    -   AWS issues.
I also added back exposed secrets to match this

2024-08-23 08:34 UTC, jakub-jarek commented
> Please review these suggestions.

Integrated most of it - there are 2 things which i didnt integrate though, at it changed meaning of things - described why underneath them

2024-08-23 15:48 UTC, jsernaque approved these changes

2024-08-23 15:48 UTC, merged