Sites landing page
edgio-docs/edgio-docs pull request #634
Opened 2022-12-14 01:16 UTC by jsernaque

2022-12-15 16:36 UTC, RaeesBhatti reviewed
I think this is a good start but it might be useful to reimagine the homepage for Edgio sites docs. For example, do the sections like Caveats and Serverless Bundle Size belong on this page? Or should we spin those as separate pages?

2022-12-15 16:36 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +{{ PRODUCT }} is available in the following global regions:
I think this should be `{{ PRODUCT }} {{ PRODUCT_PLATFORM }}`

2022-12-20 18:14 UTC, jsernaque commented
> I think this is a good start but it might be useful to reimagine the homepage for Edgio sites docs. For example, do the sections like Caveats and Serverless Bundle Size belong on this page? Or should we spin those as separate pages?

I moved that information off to a separate article called "Limits."

2022-12-22 23:26 UTC, RaeesBhatti requested changes
Thank you putting this together @jsernaque . I left some comments for you consideration

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +-   When a client requests a page through Server-Side Rendering (SSR). SSR generates static pages through our Serverless Compute workers. In addition to either eliminating the need for web servers or
We should change this to focus more on SSR rather than SSG. Since other platforms were built to cater to SSG use cases and are relatively poor at SSR use cases and our platform is stronger at SSR comparatively.
In general, SSR is preferred by users over SSG because it offers similar time-to-first-byte performance through caching but is inherently dynamic.

> SSR generates static pages through our Serverless Compute workers. In addition to either eliminating the need for web servers or reducing their load, this improves performance by processing requests closer to your users.

I think we need to rephrase the above, SSR doesn't really generate static pages, that's ISR. And replaces web servers, doesn't reduce their load. The SSR requests are not processed closer to the users necessarily. They can be cached closer to the users but that's the case for SSG and ISR as well.

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +{{ PRODUCT }} {{ PRODUCT_PLATFORM }} provides over [40 popular frameworks integrations](/guides/sites_frameworks/getting_started) through which you can deploy your headless Jamstack applications to {
> you can deploy your headless Jamstack applications

Let's rephrase this to "websites and apps" or "webapps" or something similar. We don't want to give the impression that our platform enables you to develop mobile/native applications.

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +{{ PRODUCT }} {{ PRODUCT_PLATFORM }} provides over [40 popular frameworks integrations](/guides/sites_frameworks/getting_started) through which you can deploy your headless Jamstack applications to {
> property

Are we sure we want to call this property? If so, then it's okay. But let's check with the console team on what they'll be calling it. I know that it's currently called "site".

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +{{ PRODUCT }} {{ PRODUCT_PLATFORM }} is available in the following global regions:
Let's make sure that the readers understand the these are the regions where the compute is available; the cache will be distributed to 100s of PoPs around the world, closer to end users.

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +-   Load balancing computing requests between redundant processes.
Not sure about this one. I don't think we're doing any load balancing based on usage. @phdunham can you confirm please!

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks/limits.md
> +In a lot of scenarios, NodeJS native extensions might be required to perform specific tasks related to your application.
```suggestion
In a lot of scenarios, NodeJS native extensions might be required in order to perform specific tasks related to your application.
```

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks/limits.md
> +to store permanent file storage. These external services can be Amazon S3, Google Cloud Storage, or any other storage.
```suggestion
to store permanent file storage. These external services can be Amazon S3, Google Cloud Storage, or any other storage service.
```

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks/limits.md
> +### Possible Fix [1]: Segregating devDependencies from dependencies {/*possible-fix-1-segregating-devdependencies-from-dependencies*/}
```suggestion
### [1]: Segregating devDependencies from dependencies {/*possible-fix-1-segregating-devdependencies-from-dependencies*/}
```

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks/limits.md
> +### Possible Fix [2]: Segregating assets from serverless bundle {/*possible-fix-2-segregating-assets-from-serverless-bundle*/}
```suggestion
### [2]: Segregating assets from serverless bundle {/*possible-fix-2-segregating-assets-from-serverless-bundle*/}
```

2022-12-22 23:26 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks/limits.md
> +### Possible Fix [3]: Computing which node_modules be included in the serverless bundle {/*possible-fix-3-computing-which-node_modules-be-included-in-the-serverless-bundle*/}
```suggestion
### [3]: Computing which node_modules be included in the serverless bundle {/*possible-fix-3-computing-which-node_modules-be-included-in-the-serverless-bundle*/}
```

2022-12-23 01:39 UTC, RaeesBhatti submitted a review, later dismissed
Looks excellent! Suggested some changes that I think will resonate more with web devs.

2022-12-23 01:39 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
>  title: Sites (Frameworks)
```suggestion
title: Sites
```

2022-12-23 01:39 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +{{ PRODUCT }} {{ PRODUCT_PLATFORM }}, which provides optimal performance for your Jamstack sites or applications, is powered by [{{ PRODUCT }} {{ PRODUCT_EDGE }}](/guides/performance). This means tha
```suggestion
{{ PRODUCT }} {{ PRODUCT_PLATFORM }} is a Jamstack platform built from the group up to run high-performance websites and web apps. It is the only Jamstack platform with an integrated world-class CDN [{{ PRODUCT }} {{ PRODUCT_EDGE }}](/guides/performance) and state-of-the-art [web security suite](/guides/security). {{ PRODUCT }} {{ PRODUCT_PLATFORM }} enables you to build your web apps faster and leverage a global CDN in the application code to achieve the best performance in production. 
```

2022-12-23 01:39 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +Build upon these performance improvements through Server-Side Rendering (SSR). SSR allows you to compute code embedded within your web application using our Serverless Compute workers. Processing you
```suggestion
Build upon these performance improvements through Server-Side Rendering (SSR). {{ PRODUCT }} {{ PRODUCT_PLATFORM }} takes an SSR-first approach and enables you to render your web apps using our Serverless Compute at any scale. This means that you don't have to maintain and scale the backend server infrastructure and your teams can focus on shipping features your customers will love. {{ PRODUCT }} {{ PRODUCT_PLATFORM }} improves real-world performance through [fine-grained caching](/guides/performance/caching#cache-key), allowing you to cache highly dynamic content. Responses served from the CDN cache will achieve a comparable Time to First Byte (TTFB) as static cached content.
```

2022-12-23 01:39 UTC, RaeesBhatti commented on src/pages/guides/sites_frameworks.md
> +{{ PRODUCT }} allows you to cache and deliver your content through any of our points of presence (POPs) around the world. However, your serverless code will be computed within one of the following gl
```suggestion
{{ PRODUCT }} allows you to cache and deliver your content through any of our points of presence (POPs) around the world. However, your serverless code will run in one of the following global regions:
```

2022-12-27 22:11 UTC, RaeesBhatti approved these changes
LGTM! Thank you!

2022-12-27 22:13 UTC, merged