Update v5_migration.md
edgio-docs/edgio-docs pull request #676
Opened 2023-03-07 21:17 UTC by tristanlee85

2023-03-07 21:49 UTC, RaeesBhatti requested changes

2023-03-07 21:49 UTC, RaeesBhatti commented on src/pages/guides/upgrading/v5_migration.md
> +By default, {{ PRODUCT }} {{ PRODUCT_APPLICATIONS }} version 5.1+ automatically blocks search engine traffic for edge links and permalinks. As a result, the `.noIndexPermalink()` router function serv
Let's make it explicit how we "automatically blocks search engine traffic". Let's mention the header and it's value here or link to somewhere else where it is explained.

2023-03-08 15:30 UTC, RaeesBhatti requested changes

2023-03-08 15:30 UTC, RaeesBhatti commented on src/pages/guides/upgrading/v5_migration.md
> +For {{ PRODUCT }} {{ PRODUCT_APPLICATIONS }} version 5.1 and above, the `x-robots-tag` is automatically set to `noindex` to prevent search engines from crawling edge links and permalinks. Prior to ve
```suggestion
For {{ PRODUCT }} {{ PRODUCT_APPLICATIONS }} version 5.1 and above, `x-robots-tag: noindex` header is automatically added to all responses being served from edge links and permalinks to prevent search engines from indexing those links. By default, this header will not be added to any responses served from a custom domain name. Prior to version 5.1, the `.noIndexPermalink()` function was an opt-in solution to achieve the same effect.
```

2023-03-08 16:56 UTC, RaeesBhatti requested changes

2023-03-08 16:56 UTC, RaeesBhatti commented on src/pages/guides/upgrading/v5_migration.md
> +  {{ PRODUCT }} {{ PRODUCT_APPLICATIONS }} version 5.1+ [.noIndexPermalink() is now deprecated](#permalink-indexing), since we now automatically block search engine traffic for edge links and permali
```suggestion
  {{ PRODUCT }} {{ PRODUCT_APPLICATIONS }} version 5.1+ [.noIndexPermalink() is now deprecated](#permalink-indexing), since we now instruct search engines to not index pages on edge links and permalinks by default.
```

2023-03-08 16:57 UTC, RaeesBhatti submitted a review, later dismissed
LGTM

2023-03-08 17:00 UTC, tristanlee85 commented on src/pages/guides/upgrading/v5_migration.md
> +  {{ PRODUCT }} {{ PRODUCT_APPLICATIONS }} version 5.1+ [.noIndexPermalink() is now deprecated](#permalink-indexing), since we now automatically block search engine traffic for edge links and permali
This is good, moved it over to the v6 guide as well.

2023-03-08 17:07 UTC, merged