[COMSUP-154] Edge functions caching
edgio-docs/edgio-docs pull request #903
Opened 2023-10-13 15:32 UTC by tristanlee85

2023-11-03 18:21 UTC, tristanlee85 commented
@jsernaque you are welcome to review the content, but won't release this until the feature is ready.

2023-11-03 18:44 UTC, jsernaque commented on src/guides/v7/edge_functions.md
> +Caching fetch requests within your edge function can reduce the load on your origins and deliver content faster to your users. It's important to be aware of [time limitations](#limitations) of edge f
Consider:
```suggestion
Caching fetch requests within your edge function can reduce the load on your origins and deliver content faster to your users. It may also mitigate timeout issues due to an edge function exceeding the [walltime limit](#limitations).
```

2023-11-16 21:33 UTC, RaeesBhatti commented on src/config/v7.nav.js
> +      path: 'edge_functions',
😢

2023-11-16 22:30 UTC, tristanlee85 commented on src/config/v7.nav.js
> +      path: 'edge_functions',
When this article was added, it accidentally went against the filename pattern that we have for all the other guides. @jsernaque and I talked about correcting it to be in line with the rest. It's not critical that we do other than for consistency.

2023-11-17 14:29 UTC, RaeesBhatti requested changes
Let's split this into two different PRs, one about the caching behavior right now and one fetch cache options that will be available at the end of November.

2023-11-17 14:29 UTC, RaeesBhatti commented on src/guides/v7/edge_functions.md
> +    },
This is not available right now. It will probably be available at the end of November.

2023-11-17 14:29 UTC, RaeesBhatti commented on src/guides/v7/edge_functions.md
> +These caching options provide you with granular control over how your fetch requests are cached and served, allowing you to optimize the performance of your edge function.
Not available right now.

2023-11-17 14:29 UTC, RaeesBhatti commented on src/guides/v7/edge_functions.md
> +Edge function subrequests are cached at the edge for 5 minutes by default. This means that if you make a fetch request to the same URL within 5 minutes, the response will be served from the cache ins
> Edge function subrequests are cached at the edge for 5 minutes by default

This statement is too broad. We only cache requests for 5 minutes that don't have explicit `Cache-Control` response headers **and** that are considered "cachable".

If a response has valid `Cache-Control` headers, they will be respected.

2023-11-30 17:09 UTC, RaeesBhatti submitted a review, later dismissed
Let's publish this instead of waiting any further!

2023-12-01 17:39 UTC, jsernaque commented on src/guides/v7/edge_functions.md
> +- The origin does not offer a `Cache-Control` header in the response.
```suggestion
- The response from the origin does not include a `Cache-Control` header.
```

2023-12-01 17:49 UTC, jsernaque commented on src/guides/v7/edge_functions.md
> +- If the response is cached based on the above logic, subsequent fetch requests will fetch from the cache, and only go to the origin if the response has expired or doesn't exist in the cache.
```suggestion
- If the response is cached based on the above logic, subsequent fetch requests will be served from cache until the cached response has expired or been purged. At which point, the fetch request will go to the origin.
```

2023-12-01 18:57 UTC, tristanlee85 commented on src/guides/v7/edge_functions.md
> +- If the CDN determines that the response can be cached, it will be cached for 5 minutes on the edge.
```suggestion
```

2023-12-01 19:07 UTC, jsernaque approved these changes

2023-12-01 20:29 UTC, merged